"""Foggy Cityscapes dataset loader.

Loads foggy images with corresponding clear images, depth maps, and YOLO labels.

Expected structure (matches actual downloaded data):
  data/cityscapes/
    leftImg8bit_trainvaltest/leftImg8bit/{train,val}/{city}/{base}_leftImg8bit.png
    leftImg8bit_trainval_foggyDBF/leftImg8bit_foggyDBF/{train,val}/{city}/{base}_foggy_beta_{0.005,0.01,0.02}.png
    disparity_trainvaltest/disparity/{train,val}/{city}/{base}_disparity.png
    labels/{train,val}/{city}/{base}.txt  (YOLO format, generated by convert_cityscapes_labels.py)
"""

import os
from typing import Optional, List, Dict

import torch
from torch.utils.data import Dataset
from PIL import Image
import numpy as np

from .transforms import get_train_transforms, get_val_transforms
from .depth_utils import disparity_to_depth


class FoggyCityscapesDataset(Dataset):
    """
    Foggy Cityscapes dataset with foggy image, clear GT, depth GT, and YOLO labels.

    Args:
        root: Cityscapes root directory (containing leftImg8bit_trainvaltest/, etc.)
        split: 'train' or 'val'
        fog_density: '0.005', '0.01', or '0.02' (default: '0.02' = densest)
        input_size: target image size (default 640)
        load_clear: whether to load clear GT images (default True)
        load_depth: whether to load depth maps (default True)
        config: optional config object
    """

    def __init__(
        self,
        root: str,
        split: str = 'train',
        fog_density: str = '0.02',
        input_size: int = 640,
        load_clear: bool = True,
        load_depth: bool = True,
        config=None,
    ):
        self.root = root
        self.split = split
        self.fog_density = fog_density
        self.input_size = input_size
        self.load_clear = load_clear
        self.load_depth = load_depth
        self.config = config

        # Directory paths matching actual data layout
        self.foggy_dir = os.path.join(
            root, 'leftImg8bit_trainval_foggyDBF', 'leftImg8bit_foggyDBF', split
        )
        self.clear_dir = os.path.join(
            root, 'leftImg8bit_trainvaltest', 'leftImg8bit', split
        )
        self.disp_dir = os.path.join(
            root, 'disparity_trainvaltest', 'disparity', split
        )
        self.label_dir = os.path.join(root, 'labels', split)

        # Collect valid samples
        self.samples = self._collect_samples()

        # Transforms
        if split == 'train':
            self.transform = get_train_transforms(input_size)
        else:
            self.transform = get_val_transforms(input_size)

    def _collect_samples(self) -> List[Dict]:
        """Collect all valid sample paths."""
        samples = []

        if not os.path.exists(self.foggy_dir):
            print(f"WARNING: Foggy directory not found: {self.foggy_dir}")
            return samples

        # Walk through city directories
        for city in sorted(os.listdir(self.foggy_dir)):
            city_dir = os.path.join(self.foggy_dir, city)
            if not os.path.isdir(city_dir):
                continue

            for fname in sorted(os.listdir(city_dir)):
                # Match specific fog density
                suffix = f'_foggy_beta_{self.fog_density}.png'
                if not fname.endswith(suffix):
                    continue

                # Base name: e.g., "aachen_000000_000019"
                base = fname.replace(suffix, '').replace('_leftImg8bit', '')

                foggy_path = os.path.join(city_dir, fname)
                clear_path = os.path.join(self.clear_dir, city, f"{base}_leftImg8bit.png")
                disp_path = os.path.join(self.disp_dir, city, f"{base}_disparity.png")
                label_path = os.path.join(self.label_dir, city, f"{base}.txt")

                # Check required files exist
                if not os.path.exists(foggy_path):
                    continue
                if self.load_clear and not os.path.exists(clear_path):
                    continue
                if self.load_depth and not os.path.exists(disp_path):
                    continue

                # Label file may not exist (image with no objects)
                # That's OK — we'll return empty bboxes

                samples.append({
                    'foggy': foggy_path,
                    'clear': clear_path if os.path.exists(clear_path) else None,
                    'disparity': disp_path if os.path.exists(disp_path) else None,
                    'label': label_path if os.path.exists(label_path) else None,
                    'city': city,
                    'base': base,
                })

        return samples

    def __len__(self):
        return len(self.samples)

    def _load_yolo_labels(self, label_path: str) -> torch.Tensor:
        """Load YOLO format labels from .txt file. Returns [N, 5] tensor."""
        if label_path is None or not os.path.exists(label_path):
            return torch.zeros((0, 5), dtype=torch.float32)

        bboxes = []
        with open(label_path, 'r') as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) == 5:
                    cls, cx, cy, w, h = float(parts[0]), float(parts[1]), float(parts[2]), float(parts[3]), float(parts[4])
                    bboxes.append([cls, cx, cy, w, h])

        if len(bboxes) == 0:
            return torch.zeros((0, 5), dtype=torch.float32)

        return torch.tensor(bboxes, dtype=torch.float32)

    def __getitem__(self, idx: int) -> Dict[str, torch.Tensor]:
        sample = self.samples[idx]

        # Load foggy image
        foggy = Image.open(sample['foggy']).convert('RGB')
        foggy = torch.from_numpy(np.array(foggy)).permute(2, 0, 1).float() / 255.0

        # Load clear image
        clear = None
        if self.load_clear and sample['clear'] is not None:
            clear = Image.open(sample['clear']).convert('RGB')
            clear = torch.from_numpy(np.array(clear)).permute(2, 0, 1).float() / 255.0

        # Load depth from disparity
        depth = None
        if self.load_depth and sample['disparity'] is not None:
            depth_np = disparity_to_depth(sample['disparity'])
            depth = torch.from_numpy(depth_np).unsqueeze(0).float()  # [1, H, W]

        # Load labels
        bboxes = self._load_yolo_labels(sample['label'])

        # Build target dict for synchronized transforms
        target = {
            'clear_gt': clear,
            'depth_gt': depth,
            'bboxes': bboxes,
        }

        # Apply transforms
        foggy, target = self.transform(foggy, target)

        return {
            'image': foggy,
            'clear_gt': target['clear_gt'],
            'depth_gt': target['depth_gt'],
            'bboxes': target['bboxes'],
            'image_path': sample['foggy'],
        }
